collections:
  examples:
    output: true
    permalink: /domorphic/:path
    sort_by: order
  bp: 
    output: true
    permalink: /bp/:path
    sort_by:  order

include: ['examples/source','examples/includes', 'bp/source', 'bp/assets']

defaults:   
  - scope:
      path: ""
      type: "examples"
    values: 
      layout:   "example"
      js:       true
      app:      true
  - scope:
      path: ""
      type: "bp"
    values: 
      layout:   "bp"
      math:     2
      js:       true
      bp:       true
