collections:
  examples:
    output: true
    permalink: /domorphic/:path
    sort_by: order

include: ['examples/source','examples/includes']

defaults:   
  - scope:
      path: ""
      type: "examples"
    values: 
      layout:   "example"
      js:       true
      app:      true

sass:
    sass_dir: _sass
